apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  namespace: dev
spec:
  initContainers:
    - name: configurer
      image: busybox:1.36.1
      command: ['sh', '-c', 'df -TH']
  containers:
    - name: nginx-app
      image: nginx:latest
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"

