apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels:
    name: flask-app
spec:
  containers:
  - name: flask-app
    image: kaustavhalder/test-py-app:1.0.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      httpGet:
        path: /
        port: 5000
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 5
      failureThreshold: 3
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5000
        name: http
        protocol: TCP
