apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  # labels:
  #   name: flask-app
spec:
  # volumes:
  #   - name: "flask-data"
  #     hostPath:
  #       path: "./sample"
  containers:
  - name: flask-app
    image: kaustavhalder/test-py-app:1.0.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      httpGet:
        path: /
        port: 5000
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 5
      failureThreshold: 3
    resources:
      requests:
        cpu: "500m"
        memory: "128Mi"
      limits:
        memory: "256Mi"
        cpu: "1000m"
    # volumeMounts:
    #   - mountPath: "/data"
    #     name: "flask-data"
    ports:
      - containerPort: 5000
        name: http
        protocol: TCP
