apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cache
  namespace: dev
  labels:
    app: app-cache
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          image: memcached:1.6.10
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
