# this is for ephemeral storage
apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  namespace: ckad-prep
spec:
  volumes:
    - name: nginx-run
      emptyDir: {}
    - name: nginx-data
      emptyDir: {}
    - name: nginx-cache
      emptyDir: {}
  containers:
    - name: nginx-app
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: /var/run
          name: nginx-run
        - mountPath: /var/cache/nginx
          name: nginx-cache
        - mountPath: /usr/local/nginx
          name: nginx-data
      ports:
        - containerPort: 80
